### ISSUE TITLE
register to right click menu

### ISSUE THREAD

**Issue by pcause** [wenlzhang/obsidian-task-marker#17]
I would be great to have the various items registered to the right click menu when the box is selected.  TC does this and it is very handy.

**Comment by wenlzhang** [comment]
> I would be great to have the various items registered to the right click menu when the box is selected.

Can you be more specific which commands do not show up in the right click menu? Does restart Obsidian help resolve the issue?

In the current implementation, certain settings require restarting Obsidian for them to take effect. I guess I need to figure out how to improve this point, or at least be more specific which settings need restart.

**Comment by pcause** [comment]
ok, not sure if I understand.  

first, the "cycled task statuses" section stuff is very unclear as to what it is/does and the example doesn't have any meaning, at least to me.

the add menu items, to me meant to the ctrl-p menu.  does it instead mean to the right click menu?  not clear.  tied and it does.  specifically indicate that it adss the item to the right click menu, please.

**Comment by pcause** [comment]
tried to put characters in the cycle,  used ">!?ix".  new task and right licked, selected cycle and nothing happened.

**Comment by wenlzhang** [comment]
> tried to put characters in the cycle, used ">!?ix". new task and right licked, selected cycle and nothing happened.

Would restart Obsidian help resolve this issue?

Can you see any messages related to Task Marker from the developer console? You can access the console from the Obsidian toolbar: View > Toggle Developer Tools

**Comment by wenlzhang** [comment]
> tried to put characters in the cycle, used ">!?ix". new task and right licked, selected cycle and nothing happened.

I released a new version. Could you try if it resolves the issue for you?
https://github.com/wenlzhang/obsidian-task-marker/releases/tag/0.3.2

**Comment by wenlzhang** [comment]
Closing this for now. Please re-open this if still having issues with this.
