### ISSUE TITLE
"cycle task status" doesn't cycle for tab-indented items (e.g with Outliner plugin)

### ISSUE THREAD

**Issue by davidlee** [wenlzhang/obsidian-task-marker#19]
when I repeatedly trigger cycle task status, either from a hotkey or right menu, it just sets the task to the first configured character for "cycle task status" and it stays there. Nothing in the developer console. 

weird one here as I'm sure it was working at some point, but I've reinstalled and can't seem to make it behave.

here's my config, can't see how it'd be an issue here ... maybe a plugin conflict?

```json
{
  "removeExpression": "",
  "appendDateFormat": "",
  "appendTextFormatMark": "",
  "appendTextFormatMarkRow2": "",
  "appendTextFormatCreation": "",
  "appendTextFormatAppend": "",
  "appendRemoveAllTasks": false,
  "incompleteTaskValues": " ",
  "incompleteTaskValuesRow2": "",
  "cycleTaskValues": "-x?",
  "onlyLowercaseX": true,
  "supportCanceledTasks": true,
  "previewOnClick": false,
  "rightClickComplete": true,
  "rightClickMark": true,
  "rightClickCycle": true,
  "rightClickCreate": true,
  "rightClickAppend": true,
  "rightClickResetTask": true,
  "rightClickResetAll": false,
  "rightClickToggleAll": false
}
```

**Comment by wenlzhang** [comment]
> maybe a plugin conflict

It could be like this. The following plugin may be used to check which plugin it could conflict with.
https://github.com/chrisgrieser/obsidian-divide-and-conquer

To help locate the issue, could you also try the following:

- Try to install the plugin in a new vault and only install Task Marker
- Send me the task text you are trying to cycle tasks with

**Comment by davidlee** [comment]
- ✅ new vault: works as intended.
- ❌ existing vault, disabling all other plugins (whether with divide & conquer, or manual). Tried reloading, restarting, etc. Tried removing and reinstalling Task Marker. 🤷 

nothing relevant about the task text, it's unaffected by the content and happens even with an empty task.

For now I'm using https://github.com/thingnotok/obsidian-toggle-list to replace the cycle behaviour, but would prefer just using task marker.

**Comment by davidlee** [comment]
Oh man, I can't believe it took me this long to figure this out: I was wrong, it IS dependent on the task text — leading whitespace! I'm using the Outliner plugin, and `cycle task status` only works correctly at the outermost level of indentation (FWIW, I'm using tabs for indentation):

```
- [>] ✅ works
	- [x] nope
		- [x] nope
			- [x] nope
```

**Comment by davidlee** [comment]
Note: using e.g. `mark task` with the menu works just fine with these indented list items.

**Comment by wenlzhang** [comment]
Thanks for the detailed information!

I have a few ideas regarding how to resolve this issue. Will post any update here.

**Comment by wenlzhang** [comment]
I published a new version that should have resolved the issue. Could you try this new version?
https://github.com/wenlzhang/obsidian-task-marker/releases/tag/0.3.2

**Comment by davidlee** [comment]
@wenlzhang Nice! ✅ Solves the issue perfectly, thanks!
