### ISSUE TITLE
should Reset All Completed Tasks (optionally) remove completion dates?

### ISSUE THREAD

**Issue by davidlee** [wenlzhang/obsidian-task-marker#27]
just what it says on the tin — for my use case it'd be preferable when resetting a checklist to remove the prior completion dates, of a format like:

```
- [ ] do this thing again ✅ 2023-01-27
```

Not a high priority, and may be fiddly if accounting for configuration (optionality; all possible variations, etc), but figured it'd be worth logging.

**Comment by wenlzhang** [comment]
Thanks for the feedback!

Unfortunately, I was considering removing features that operate on all tasks. This is why this feature was not described in the documentation.

One focus of Task Marker in the future would be operating on single tasks, to simplify the development.

One can use [Task Collector](https://github.com/ebullient/obsidian-task-collector) for features like moving and resetting all completed tasks.

**Comment by davidlee** [comment]
Roger. 

It's nice have an all-in-one, but I can appreciate the maintenance benefits of a more focused set of features - it makes sense to me. Good on you for having the (uncommon) sense to remove, rather than just add, features.
