### ISSUE TITLE
Bug in appending text which has text and colon on marking complete a task

### ISSUE THREAD

**Issue by bhavul** [wenlzhang/obsidian-task-marker#28]
### Let's say I've got this example of a task: 
<img width="679" alt="Screenshot 2023-02-05 at 05 26 32" src="https://user-images.githubusercontent.com/5140951/216803289-87270683-996f-491a-9b24-a6f8ccc2b916.png">

### Here are the settings for completed task appending text
<img width="801" alt="Screenshot 2023-02-05 at 05 26 55" src="https://user-images.githubusercontent.com/5140951/216803298-c6e97910-3ac5-4151-876a-73249c0ca34c.png">

### When I mark the task complete via menu, It works. 
<img width="441" alt="Screenshot 2023-02-05 at 05 27 21" src="https://user-images.githubusercontent.com/5140951/216803314-ac532b6d-1391-4e12-a70d-30c2a1199a37.png">

### However, if the text that needs to be appended has any text followed by a colon or two, like below
<img width="889" alt="Screenshot 2023-02-05 at 05 28 06" src="https://user-images.githubusercontent.com/5140951/216803342-2d47d2e0-afa1-45c8-99e0-0d47e966e62d.png">

### It ends up producing gibberish text. 
<img width="566" alt="Screenshot 2023-02-05 at 05 28 49" src="https://user-images.githubusercontent.com/5140951/216803364-80891d36-484e-43e7-a893-75c3a7cf0f76.png">

It can always be reproduced.

**Steps I've tried to debug**:
1. Restarted Obsidian, and Vault
2. Disable any other task related plugins
3. Try changing the appending text. -- Issue is there as long as a single `:` would be there following some text. E.g. `test: YYYY-MM-DD` would also cause gibberish text to appear. 

**Consequence of this**
We can not use the plugin to append dataview related field for completion or progress of task to the task.

**Comment by wenlzhang** [comment]
Could you try updating the setting to `[[complete:: ]YYYY-MM-DD[]]` and see if it resolves the issue for you?

**Comment by bhavul** [comment]
That worked, thanks for the solution. It may be useful to add this in documentation somewhere?

**Comment by wenlzhang** [comment]
> It may be useful to add this in documentation somewhere?

Indeed. Will do that later.

**Comment by wenlzhang** [comment]
Updated the documentation on this as follows:

https://github.com/wenlzhang/obsidian-task-marker#how-to-configure
