### ISSUE TITLE
Create separate command for cancel task

### ISSUE THREAD

**Issue by vanadium23** [wenlzhang/obsidian-task-marker#32]
Currently plugin has to command:
* mark as completed
* cycle custom statuses

It would be great to have separate command to cancel.

Or best way, to provide custom statuses to separate command and right click menu.

**Comment by wenlzhang** [comment]
> It would be great to have separate command to cancel.

If "Support canceled tasks" is enabled in settings, there would be a separate command for cancelling tasks. Would this satisfy you needs?

> Or best way, to provide custom statuses to separate command and right click menu.

If task statuses are set in the "Marking tasks" section of settings, there should be separate commands for each status. Please try to restart Obsidian, if they do not show up. Does this work for you?

Regarding custom statuses in right click menu, does the mark task modal work for you? To use this, try to enable "Add menu item for marking a task", then you would see a command in the right click menu.

**Comment by vanadium23** [comment]
> If "Support canceled tasks" is enabled in settings, there would be a separate command for cancelling tasks. Would this satisfy you needs?

Definitely!

**Comment by vanadium23** [comment]
Sorry, just notices that two options add cancel task command and option in context menu.
