### ISSUE TITLE
Commands as "right click context menu items" no longer work

### ISSUE THREAD

**Issue by ekclau** [wenlzhang/obsidian-task-marker#50]
After choosing in Settings which commands to add to the "right click context menu", they do show up in the context menu.
However, when actually clicking those items in the context menu, they have no effect on the task concerned.

**Comment by wenlzhang** [comment]
Thanks for the feedback!

Recently, I have a busy schedule, but I will debug this and get back to you as soon as possible.

**Comment by wenlzhang** [comment]
@ekclau I released a new version 0.4.2. Could you please try if it resolves the issue for you?

**Comment by ekclau** [comment]
@wenlzhang  Many thanks for looking into it. Yes, your new version works well.
