### ISSUE TITLE
Support all un-ordered list markers

### ISSUE THREAD

**Issue by vorpalvorpal** [wenlzhang/obsidian-task-marker#72]
According to the [markdown spec](https://www.markdownguide.org/basic-syntax/#unordered-lists) the following are all allowable syntax for unordered lists: `*`,`-`,`+`

At present, obsidian-task-marker only seems to recognise `-`

If I create the following list:
```
* item with an asterisk
- item with a dash
+ item with a plus
```
and then run the task-marker plugin on it I get:
```
* item with an asterisk
- [ ] item with a dash
+ item with a plus
```

**Comment by vorpalvorpal** [comment]
I fixed this by changing lines 60-65 in `main.js`, which I believe correspond to lines 20-25 is `taskmarker-TaskMarker.ts`:

original:
```
    this.anyListItem = new RegExp(/^([\s>]*- )([^\\[].*)$/);
    this.anyTaskMark = new RegExp(/^([\s>]*- \[)(.)(\] .*)$/);
    this.blockQuote = new RegExp(/^(\s*>[\s>]*)(.*)$/);
    this.blockRef = new RegExp(/^(.*?)( \^[A-Za-z0-9-]+)?$/);
    this.continuation = new RegExp(/^( {2,}|\t)/);
    this.stripTask = new RegExp(/^([\s>]*-) \[.\] (.*)$/);
```

changed:
```
    this.anyListItem = new RegExp(/^([\s>]*[-+*] )([^\\[].*)$/);
    this.anyTaskMark = new RegExp(/^([\s>]*[-+*] \[)(.)(\] .*)$/);
    this.blockQuote = new RegExp(/^(\s*>[\s>]*)(.*)$/);
    this.blockRef = new RegExp(/^(.*?)( \^[A-Za-z0-9-]+)?$/);
    this.continuation = new RegExp(/^( {2,}|\t)/);
    this.stripTask = new RegExp(/^([\s>]*[-+*]) \[.\] (.*)$/);
```

That is changing the `-` in the regexs for `anyListItem`, `anyTaskMark` and `stripTask` to `[-+*]`

**Comment by wenlzhang** [comment]
@vorpalvorpal Thank you for the request and code!

I also updated some other parts of the code (https://github.com/wenlzhang/obsidian-task-marker/commit/2c55c7ba51753bdc3f401e5a417aa61c6cd014b8) and released a new version.

- https://github.com/wenlzhang/obsidian-task-marker/releases/tag/0.4.3

Can you test if it works for you?

**Comment by wenlzhang** [comment]
Closing this for now. Please comment here if the new version does not satisfy your needs.
