### ISSUE TITLE
Cycling tasks doesn't append text automatically

### ISSUE THREAD

**Issue by EarthToMooney** [wenlzhang/obsidian-task-marker#73]
When using the command "Task Marker: Cycle Task Status" to cycle to a completed status, it doesn't seem to append the text I specified for completed tasks. Here are my settings:
![image](https://github.com/wenlzhang/obsidian-task-marker/assets/77983993/0f0b9b28-c536-4f4a-b7cb-0cab8aaffd17)
![image](https://github.com/wenlzhang/obsidian-task-marker/assets/77983993/d2dd4879-32e6-457a-982d-d43fdc397793)
![image](https://github.com/wenlzhang/obsidian-task-marker/assets/77983993/fee67825-a3c1-41e7-9728-c074b6dbdc47)

**Comment by wenlzhang** [comment]
> When using the command "Task Marker: Cycle Task Status" to cycle to a completed status, it doesn't seem to append the text I specified for completed tasks.

This is the intended behaviour; otherwise, several texts would be appended when cycling among several statuses, which may be too much appended texts.

To append text when completing tasks, one needs to use the "Complete task" command.

**Comment by EarthToMooney** [comment]
Understood; thanks for clarifying that. I found a way using Shell Commands to do this automatically with a hotkey, so you can mark this as resolved.
