### ISSUE TITLE
Reset Task doesn't work if escape characters are included

### ISSUE THREAD

**Issue by eb2ai** [wenlzhang/obsidian-task-marker#84]
If I want to include something other than strict momentjs syntax, resetting the task will fail.

Example:
\[\c\o\m\p\l\e\t\i\o\n\:\: YYYY-MM-DD\]

**Comment by wenlzhang** [comment]
Can you clarify what the appended text would look like? E.g., `- [ ] Task appended text`.

What is the task status when you try to reset the task?

Do you see any errors or messages in the console when the resetting fails? You can access the console as follows:
![](https://user-images.githubusercontent.com/44930227/276351619-d33a407a-a06e-4ba1-a471-bbdd66c945b0.png)

**Comment by eb2ai** [comment]
Thanks for looking at this.

Here are two tasks. The first one is what the output would look like. The second is what is produced.
```
- [x] 12:00 Test the way it should be [Completed:: 2023-11-04] 
- [x] 12:00 This is a test item. [Co34pl6t66: 2023-11-04]
```

My first instinct is to escape the brackets. So that is what I've done here.  I'm not sure, but this may be why most other plugins do something like this. `Whatever {Date: YYYY-MM-DD}` Allows any text to be used. This would allow any string to be used and separate from the moment.js. (I think that's what you are using)

Here is the failing string.
<img width="778" alt="Screenshot by Dropbox Capture" src="https://github.com/wenlzhang/obsidian-task-marker/assets/134644662/947ae0a8-1d41-4362-aa37-b0a436a03f7a">
Full Failing String = `\[Completed: YYYY-MM-DD\]`

**Comment by wenlzhang** [comment]
To configure the moment.js format, square brackets are needed to surround the content that is not part of the format string. For example, if `[completion::2023-01-01]` is the desired text to be appended, then `[[completion::]YYYY-MM-DD[]]` needs to be configured in settings.

In your case, if `[Completed:: 2023-11-04]` is the desired text to be appended, then `[[Completed:: ]YYYY-MM-DD[]]` needs to be configured. Can you try if this works for you?

**Comment by eb2ai** [comment]
I probably should have delved deeper into moment.js and wouldn't have had to both your with this one.  Thanks!!!!

This simple plugin has and will help me on the daily.  Thank you so much.
